#!/bin/bash

docker volume create --name beetrack-postgres
docker volume create --name beetrack-redis
docker volume create --name beetrack-bundle

docker-compose run --user "$(id -u):$(id -g)" web rake db:reset
docker-compose run --user "$(id -u):$(id -g)" web rake db:migrate

docker-compose up


## Create a job
# docker-­compose run --­­user "$(id -­u):$(id -­g)" beetrack rails g job tracker
# rails generate rspec:install
# bundle exec rspec