version: '2'

services:
  postgres:
    image: mdillon/postgis:9.5
    environment:
      POSTGRES_USER: beetrack
      POSTGRES_PASSWORD: B33tr4ck
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  web:
    build: .
    depends_on:
      - postgres
      - redis
      - geoserver
    volumes:
      - .:/beetrack
#      - bundle:/bundle
    ports:
      - '8000:8000'
    env_file:
      - .beetrack.env

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/beetrack
      - bundle:/bundle
    env_file:
      - .beetrack.env

  geoserver:
    image: kartoza/geoserver
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - geoserver:/opt/geoserver/data_dir

volumes:
  redis:
  postgres:
  geoserver:
  bundle: